name: chromium
version: 69.0.3497.42
summary: Chromium web browser, open-source version of Chrome
description: |
 An open-source browser project that aims to build a safer, faster, and more
 stable way for all Internet users to experience the web.
confinement: strict

apps:
  chromium:
    command: desktop-launch chromium.launcher
    desktop: bin/chromium.desktop
    environment:
      DISABLE_WAYLAND: 1
      CHROME_DESKTOP: chromium.desktop
    plugs:
      - browser-sandbox
      - camera
      - cups-control
      - desktop
      - gsettings
      - home
      - mount-observe
      - network
      - network-manager
      - opengl
      - password-manager-service
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - unity7 # required for xdg-open to work
      - upower-observe
      - x11

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

parts:
  # Launchpad builders have a timeout for how long they are allowed to access
  # the internet (through a proxy) starting from the start of the build.
  # Since the chromium part takes a long time to build, we need to ensure
  # that all other parts that need to access the internet (to e.g. fetch build
  # or stage packages) are built before it (before the proxy authentication is
  # revoked).

  chromium:
    plugin: nil
    source: https://commondatastorage.googleapis.com/chromium-browser-official/chromium-69.0.3497.42.tar.xz
    source-checksum: sha512/fb410149b6a55f0d80c9a64fcb7e7b65b17abfcfc0c942d58fa2c6bd89f3726decc953da260e8c83020ac8f795d08327ec154337b2488b959c5845947b94e958
    after: [launcher]
    build-packages:
      - quilt
      - autoconf
      - automake
      - ninja-build
      - pkg-config
      - lsb-release
      - python
      - bison
      - flex
      - gawk
      - git
      - gperf
      - subversion
      - cmake
      - libxml2-dev
      - libpulse-dev
      - libcups2-dev
      - libasound2-dev
      - libnss3-dev
      - mesa-common-dev
      - libgles2-mesa-dev
      - libpci-dev
      - libxtst-dev
      - libxss-dev
      - libgtk-3-dev
      - libglib2.0-dev
      - libgnome-keyring-dev
      - libudev-dev
      - libdrm-dev
      - libcap-dev
      - libgcrypt-dev
      - libkrb5-dev
      - libxkbcommon-dev
      - libpam0g-dev
      - libffi-dev
      - uuid-dev
      - chrpath
      - yasm
      - shared-mime-info
      - zlib1g-dev
    stage-packages:
      - libgl1-mesa-glx
      - libgnome-keyring0
      - libnss3
      - libsecret-1-0
      - shared-mime-info
      - pulseaudio
    override-build: |
      set -eux

      QUILT_PATCHES=../../../snap/patches quilt push -a

      # Write SVN configuration file with HTTP proxy settings to work around
      # https://launchpad.net/bugs/1668358 until the fix is deployed on
      # launchpad builders.
      PROXY_HOST_PORT=$(echo $http_proxy | cut -d/ -f3)
      PROXY_HOST=$(echo $PROXY_HOST_PORT | cut -d: -f1)
      PROXY_PORT=$(echo $PROXY_HOST_PORT | cut -d: -f2)
      mkdir -p $HOME/.subversion
      cat > $HOME/.subversion/servers << EOL
      [global]
      http-proxy-host = $PROXY_HOST
      http-proxy-port = $PROXY_PORT
      EOL

      # Pre-built binaries are provided for eu-strip and clang on x86-64,
      # for all other architectures they have to be built from source.
      if [ $(arch) = "x86_64" ]; then
        tools/clang/scripts/update.py
      else
        cd third_party/eu-strip
        ./build.sh
        cd ../..
        tools/clang/scripts/update.py --force-local-build --without-android --gcc-toolchain=/usr --use-system-cmake
      fi

      # Build GN
      export CXX=$PWD/third_party/llvm-build/Release+Asserts/bin/clang++
      export AR=$PWD/third_party/llvm-build/Release+Asserts/bin/llvm-ar
      tools/gn/bootstrap/bootstrap.py

      # Build chromium
      OUT=out/Release
      mkdir -p $OUT
      cp ../../../snap/args.gn $OUT/
      $OUT/gn gen $OUT
      ninja -C $OUT chrome chrome_sandbox chromedriver

      # Strip debug symbols off the chrome binary
      python build/gn_run_binary.py ./third_party/eu-strip/bin/eu-strip -o $OUT/chrome.stripped -f $OUT/chrome.debug $OUT/chrome
      mv $OUT/chrome.stripped $OUT/chrome

      # Install to $SNAPCRAFT_PART_INSTALL
      mkdir -p $SNAPCRAFT_PART_INSTALL
      cp chrome/app/theme/chromium/product_logo_256.png $SNAPCRAFT_PART_INSTALL/chromium.png
      T=$SNAPCRAFT_PART_INSTALL/usr/lib/chromium-browser
      mkdir -p $T
      cd $OUT
      cp chrome chrome_*.pak headless_lib.pak icudtl.dat \
          libffmpeg.so natives_blob.bin resources.pak \
          snapshot_blob.bin v8_context_snapshot.bin \
          $T/
      cp chrome_sandbox $T/chrome-sandbox
      mkdir $T/locales
      cp locales/*.pak $T/locales/
      mkdir $T/swiftshader
      cp swiftshader/*.so $T/swiftshader/

      # Fix setuid bits on the sandbox executable
      # (ref: https://forum.snapcraft.io/t/call-for-testing-chromium-snap/1714/16)
      chmod 4555 $SNAPCRAFT_PART_INSTALL/usr/lib/chromium-browser/chrome-sandbox

      # Add data-dir mount layout to the snap as a temporary workaround until
      # https://github.com/snapcore/snapd/pull/5395 lands in snapd.
      mkdir -p $SNAPCRAFT_PART_INSTALL/data-dir/{icons,sounds,themes}

  launcher:
    plugin: dump
    source: snap
    after: [desktop-gtk3]
    organize:
      chromium.launcher: bin/
      chromium.desktop: bin/

  shared-mime-info:
    after: [launcher, chromium]
    plugin: nil
    build-attributes: [no-system-libraries]
    override-build: |
      set -eux
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share
      cp -R $SNAPCRAFT_STAGE/usr/share/mime $SNAPCRAFT_PART_INSTALL/usr/share/
      update-mime-database $SNAPCRAFT_PART_INSTALL/usr/share/mime
    prime:
      - usr/share/mime/*
