name: chromium
version: 68.0.3440.106
summary: Chromium web browser, open-source version of Chrome
description: |
 An open-source browser project that aims to build a safer, faster, and more
 stable way for all Internet users to experience the web.
confinement: strict

apps:
  chromium:
    command: desktop-launch chromium.launcher
    desktop: bin/chromium.desktop
    environment:
      DISABLE_WAYLAND: 1
      CHROME_DESKTOP: chromium.desktop
    plugs:
      - browser-sandbox
      - camera
      - cups-control
      - desktop
      - gsettings
      - home
      - mount-observe
      - network
      - network-manager
      - opengl
      - password-manager-service
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - unity7 # required for xdg-open to work
      - upower-observe
      - x11

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true

parts:
  # Launchpad builders have a timeout for how long they are allowed to access
  # the internet (through a proxy) starting from the start of the build.
  # Since the chromium part takes a long time to build, we need to ensure
  # that all other parts that need to access the internet (to e.g. fetch build
  # or stage packages) are built before it (before the proxy authentication is
  # revoked).

  chromium:
    plugin: nil
    source: https://commondatastorage.googleapis.com/chromium-browser-official/chromium-68.0.3440.106.tar.xz
    source-checksum: sha512/ab94f89e614919932d4d960bac8e5450c4d3f26dea4892e6591762bfaeeb4707a090352d4a952bcb55e34fde4950db22a36004788efd26ffb22b28770e9795c4
    after: [launcher]
    build-packages:
      - ninja-build
      - pkg-config
      - lsb-release
      - python
      - bison
      - gperf
      - libpulse-dev
      - libcups2-dev
      - libasound2-dev
      - libnss3-dev
      - mesa-common-dev
      - libgles2-mesa-dev
      - libpci-dev
      - libxtst-dev
      - libxss-dev
      - libgtk-3-dev
      - libglib2.0-dev
      - libgnome-keyring-dev
      - libudev-dev
      - libdrm-dev
      - libcap-dev
      - libgcrypt-dev
      - libkrb5-dev
      - libxkbcommon-dev
      - libpam0g-dev
      - libffi-dev
      - chrpath
      - yasm
      - shared-mime-info
    stage-packages:
      - libgl1-mesa-glx
      - libgnome-keyring0
      - libnss3
      - libsecret-1-0
      - shared-mime-info
      - pulseaudio
    override-build: |
      set -eux
      for patch in $(cat ../../../snap/patches/series)
      do
        case "$patch" in
          \#*)
            echo "skipping $patch";;
          *)
            patch -d . -p1 < ../../../snap/patches/$patch;;
        esac
      done
      tools/clang/scripts/update.py
      common_defines="\
        google_api_key=\"AIzaSyDGQzx0c0ptZVDriLi9Wblo2voeLnmPq-o\" \
        google_default_client_id=\"424119844901-tilod0e1nm0dt85e1evrdfp3cc3ec01d.apps.googleusercontent.com\" \
        google_default_client_secret=\"WCCejhqORuxKG272GAWxsPIU\" \
        enable_hangout_services_extension=true \
        enable_mdns=true \
        enable_nacl=false \
        enable_wayland_server=false \
        enable_widevine=true \
        fieldtrial_testing_like_official_build=true \
        is_component_build=false \
        is_component_ffmpeg=true \
        is_debug=false \
        is_desktop_linux=true \
        is_official_build=true \
        remove_webcore_debug_symbols=true \
        symbol_level=0 \
        treat_warnings_as_errors=false \
        use_allocator=\"none\" \
        use_alsa=true \
        use_aura=true \
        use_cups=true \
        use_dbus=true \
        use_gio=true \
        use_glib=true \
        use_gold=false \
        use_gtk3=true \
        use_libpci=true \
        use_pulseaudio=true \
        use_sysroot=false \
        use_system_harfbuzz=false \
        use_system_libjpeg=false \
        rtc_enable_protobuf=false \
        rtc_use_h264=true \
        is_cfi=false \
        target_os=\"linux\" \
        current_os=\"linux\" \
        optimize_webui=false"
      ffmpeg_extra_defines="\
        proprietary_codecs=true \
        ffmpeg_branding=\"Chrome\""
      tools/gn/bootstrap/bootstrap.py --verbose --no-rebuild
      OUT=out/Release
      $OUT/gn gen $OUT --args="$common_defines $ffmpeg_extra_defines"
      ninja -C $OUT chrome chrome_sandbox chromedriver
      python build/gn_run_binary.py ./third_party/eu-strip/bin/eu-strip -o $OUT/chrome.stripped -f $OUT/chrome.debug $OUT/chrome
      mv $OUT/chrome.stripped $OUT/chrome
      mkdir -p $SNAPCRAFT_PART_INSTALL
      cp chrome/app/theme/chromium/product_logo_256.png $SNAPCRAFT_PART_INSTALL/chromium.png
      T=$SNAPCRAFT_PART_INSTALL/usr/lib/chromium-browser
      mkdir -p $T
      cd $OUT
      cp chrome chrome_*.pak chrome_sandbox headless_lib.pak icudtl.dat \
          libffmpeg.so natives_blob.bin resources.pak \
          snapshot_blob.bin v8_context_snapshot.bin \
          $T/
      mkdir $T/locales
      cp locales/*.pak $T/locales/
      mkdir $T/swiftshader
      cp swiftshader/*.so $T/swiftshader/
  launcher:
    plugin: dump
    source: snap
    after: [desktop-gtk3]
    organize:
      chromium.launcher: bin/
      chromium.desktop: bin/
  shared-mime-info:
    after: [launcher, chromium]
    plugin: nil
    build-attributes: [no-system-libraries]
    override-build: |
      set -eux
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share
      cp -R $SNAPCRAFT_STAGE/usr/share/mime $SNAPCRAFT_PART_INSTALL/usr/share/
      update-mime-database $SNAPCRAFT_PART_INSTALL/usr/share/mime
    prime:
      - usr/share/mime/*
